### ISSUE TITLE
Weird htop error building on Ubuntu 16.10

### ISSUE THREAD

**Issue by davembg** [escalade/LibreELEC.tv#24]
checking for refresh in -lncurses... no

htop configure can't find libncurses(?)
All other packages can link to netbsd-curses just fine.
I updated the netbsd-curses package to the latest version, no joy.

Did you do anything specific to get htop to build? or did it just work for you?

**Comment by davembg** [comment]
HTOP version 1.0.3 works - good enough:)

I changed the PKG_VERSION in the packages/escalade/sysutils/htop/package.pk to 1.0.3
and it built without issue.

**Comment by escalade** [comment]
It just works for me. I just pushed an update to htop that might fix the issue, could you test?

**Comment by davembg** [comment]
I tried it...it still fails with the same error.
What are you using to build?

**Comment by escalade** [comment]
I'm using Arch Linux.

**Comment by davembg** [comment]
I'll bet that's why. Arch's autoconf/m4 is newer.
It looks to me like the configure for htop 2.0.2 is further along than the Ubuntu 16.x toolset.

**Comment by escalade** [comment]
Well, it _should_ use the LibreELEC toolchain's autoconf and not the host system. That's kind of the whole point :) Check config.log for clues.

**Comment by davembg** [comment]
Yup, that is the point. I checked - the config script fails at the "checking for refresh" point.
I can change htop's configure, but, that's a PITA to implement. 1.0.3 is fine for this, I'll bet.
Maybe add some logic to use htop 1.0.3 for Ubuntu? dunno.... htop isn't a crucial tool, right?

**Comment by escalade** [comment]
The proper way to fix this would be to find the root cause of the problem. There is already libncurses in the toolchain, it's found and linked properly on Arch Linux. I'm not going to add a hack that uses an older version for Ubuntu, that's something you could add locally. It's not a crucial tool, you can exclude it if you like in packages/oem/package.mk. Why don't you pastebin the config.log?

**Comment by davembg** [comment]
I switched to my Arch VM.
There were also errors with cffi, so, I ditched Ubuntu.

Best I can tell, it has something to do with how Ubuntu handles the "host" and "target" builds.
Doesn't make a lot of sense to me.
